version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - xdefi-db:/var/lib/postgresql/data
    env_file:
      - db.env
  web:
    build: .
    command: uvicorn app.main:application --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - db.env
      - web.env
    depends_on:
      - db

volumes:
  xdefi-db:
