"""Added foreignkey

Revision ID: 3364952e6cd0
Revises: 9dc8c032a909
Create Date: 2022-12-09 16:26:07.496942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3364952e6cd0'
down_revision = '9dc8c032a909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('token0_id', sa.String(), nullable=True))
    op.add_column('pairs', sa.Column('token1_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pairs', 'tokens', ['token0_id'], ['id'])
    op.create_foreign_key(None, 'pairs', 'tokens', ['token1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairs', type_='foreignkey')
    op.drop_constraint(None, 'pairs', type_='foreignkey')
    op.drop_column('pairs', 'token1_id')
    op.drop_column('pairs', 'token0_id')
    # ### end Alembic commands ###
