"""Added pair and token models

Revision ID: 9dc8c032a909
Revises: 
Create Date: 2022-12-09 16:09:21.998941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc8c032a909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token0Price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('token1Price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairs_created_at'), 'pairs', ['created_at'], unique=False)
    op.create_table('tokens',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_created_at'), 'tokens', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_created_at'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_pairs_created_at'), table_name='pairs')
    op.drop_table('pairs')
    # ### end Alembic commands ###
